### ISSUE TITLE
Defer authentication when instantiating User objects

### ISSUE THREAD

**Issue by jcs** [karanlyons/chump#12]
Pushover's `/1/users/validate` endpoint is heavily rate limited and should not be used to validate a user key on every message.  A user of your library trying to send to multiple Pushover users may have their IP temporarily blocked because they are inadvertently hitting the validation endpoint too often.  You're also just generating more traffic to our API than is needed.

My advice would be to only call that endpoint when the caller explicitly asks if the user is validated.  Otherwise just send the user key as it was presented and respond accordingly (our API will return an object with the `user` key set if the `user` key supplied is invalid).

**Comment by karanlyons** [comment]
Well that’s a bummer, but I can make `User.is_authenticated` and `User.devices` lazily evaluated to avoid this. A good chunk of this library was centered around making as few requests as possible anyway.

Are there any ways to get a user’s devices (or determine if a device is valid) from a standard response outside of a call to `/1/users/validate`? It’s been a few years since I’ve used Pushover personally. Additionally, is there a log of API changes over time? A quick perusal shows a handful of new additions that likely warrant inclusion into this wrapper if I’m going to be maintaining it.

**Comment by jcs** [comment]
There is no way to get the list of devices outside of the validate call, but if you send to an invalid device, the message is just sent to all devices on the account (to avoid losing potentially important notifications).

There is no API changelog other than things mentioned on https://updates.pushover.net/

**Comment by karanlyons** [comment]
I’m going to opt for deferring a call to `/1/users/validate` until either `is_authenticated` or `devices` is accessed (including being accessed to confirm that a given device is valid), then, as I think one would prefer knowing if they've specified a nonexistent device than have a message unknowingly broadcast to more devices than they intended.
