### ISSUE TITLE
Device Empty String ValueError in 1.6.0

### ISSUE THREAD

**Issue by nscaife** [karanlyons/chump#20]
In 1.5.2, if you pass `device=''` to chump's `create_message`, Pushover will deliver the message to all devices in the account. In 1.6.0, this raises a ValueError:

`ValueError: Bad device: must be in ('v', 'w', 'x', 'y', 'z'), was ''`

I think the intended use of this was to pass (or default to) `None` for this, but urlwatch defaults `device=''`. I'm going to open an issue there as well, as I'm not sure what the desired fix is for this.

**Comment by karanlyons** [comment]
Yeah, this may have been a “mistake” insofar as not tying the change to the correct semver, however I’d argue it as correct behavior. `None` here means “no specific device” which isn’t really semantically what `''` encodes, and it’s better to catch a potential string munging issue at the client edge rather than waiting for whatever fallout it may incur. I’d advise that the default is changed in the downstream projects: a true `Nothing` type is more explicit and less prone to errors than some sentinel value in the `Just` type.
