### ISSUE TITLE
Links not clickable in pushover on Safari

### ISSUE THREAD

**Issue by ghost** [karanlyons/chump#22]
I am using chump in conjunction with [urlwatch.](https://github.com/thp/urlwatch). When links arrive they are not clickable. According to pushover support the html has been stripped from the link:

> It looks like you are receiving messages with HTML parsing enabled (https://pushover.net/api#html) so any links are expected to already be turned into links with <a href=""></a> tags. If you send without the html flag on, they should show up as links in the desktop client.
> This appears to be done differently in our iOS client which tries to find links even for HTML messages, which may be a bug there.
> --
> joshua stein | Pushover | https://pushover.net

**Comment by karanlyons** [comment]
As explained in your quote, if you have HTML styling turned on you are expected to provide HTML. A message such as `http://example.com` with HTML styling *off* will automatically be rendered into a link, but if you have HTML styling *on* you must send `<a href="http://example.com”>Clickable Text</a>` instead.

Unless I’m misunderstanding the question, this does not appear to be an issue with Chump.

**Comment by ghost** [comment]
I don’t know of a way to control those options. I haven’t turned anything on or off that I know of.

**Comment by karanlyons** [comment]
As stated in the [docs](https://chump.readthedocs.io/en/stable/api.html), the `html` kwarg to `create_message`/`send_message`/`Message`/etc., which defaults to `False`.

Note that Chump is a dependency used by urlwatch. [urlwatch sets `html=True`](https://github.com/thp/urlwatch/blob/04abd21756a45cfbb6d7d6998eabc7b9cf6c5de8/lib/urlwatch/reporters.py#L466).

**Comment by ghost** [comment]
Your'e saying html links should be coming through to pushover if I haven't set html=False in urlwatch, which I haven't.

EDIT. Sorry,, you are saying the opposite. I will see how to make that change in urlwatch.

**Comment by karanlyons** [comment]
I am saying that the framework you use to send pushover notifications uses Chump, *but that it tells Chump to set HTML styling on*. You will thus need to style your messages using HTML rather than relying on Pushover to do automatic styling. This is not an issue with Chump.

> Pushover is now allowing critical alerts. Is there any chance this will feature will be added to chump?

This feature is entirely client side, as stated in [Pushover’s announcement](https://blog.pushover.net/posts/2020/2/ios-critical-alerts). Chump already supports emergency messages as stated in [the docs](https://chump.readthedocs.io/en/stable/examples.html#sending-an-emergency-message). If urlwatch doesn’t expose this functionality then that would be an issue with urlwatch, but this is also not an issue with Chump.

**Comment by ghost** [comment]
Please don't mistake my ignorance for accusation. I couldn't find the doc for chump until you sent me the link and I didn't see the code inside of urlwatch until you sent me the link.

Thanks for the clarifications. I will go study all of this now and try to find a solution.

**Comment by karanlyons** [comment]
No worries, I mean “issue” in the Git/Hub parlance, not colloquially.
